package com.meetingm.mini.pro.dao;

import com.meetingm.mini.pro.entity.GoodsRepaty;

public interface GoodsRepatyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_repaty
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_repaty
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insert(GoodsRepaty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_repaty
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insertSelective(GoodsRepaty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_repaty
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    GoodsRepaty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_repaty
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsRepaty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_repaty
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKey(GoodsRepaty record);
}