package com.meetingm.mini.pro.dao;

import com.meetingm.mini.pro.entity.GoodsBorrow;

public interface GoodsBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_borrow
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_borrow
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insert(GoodsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_borrow
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insertSelective(GoodsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_borrow
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    GoodsBorrow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_borrow
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_borrow
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKey(GoodsBorrow record);
}