package com.meetingm.mini.pro.dao;

import com.meetingm.mini.pro.entity.GoodsSell;

public interface GoodsSellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sell
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sell
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insert(GoodsSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sell
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insertSelective(GoodsSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sell
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    GoodsSell selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sell
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sell
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKey(GoodsSell record);
}