package com.meetingm.mini.pro.dao;

import com.meetingm.mini.pro.entity.SysroleUser;

public interface SysroleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysrole_user
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysrole_user
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insert(SysroleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysrole_user
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insertSelective(SysroleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysrole_user
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    SysroleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysrole_user
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKeySelective(SysroleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysrole_user
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKey(SysroleUser record);
}