package com.meetingm.mini.pro.dao;

import com.meetingm.mini.pro.entity.UserBinding;

public interface UserBindingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_binding
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_binding
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insert(UserBinding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_binding
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int insertSelective(UserBinding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_binding
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    UserBinding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_binding
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKeySelective(UserBinding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_binding
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    int updateByPrimaryKey(UserBinding record);
}