package com.meetingm.mini.pro.entity;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.brand
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.component
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.code
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.producted_date
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date productedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.indate
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.lastCatId
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer lastcatid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.catPath
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private String catpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.isDel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.brand
     *
     * @return the value of t_goods.brand
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.brand
     *
     * @param brand the value for t_goods.brand
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.component
     *
     * @return the value of t_goods.component
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.component
     *
     * @param component the value for t_goods.component
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.code
     *
     * @return the value of t_goods.code
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.code
     *
     * @param code the value for t_goods.code
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.unit
     *
     * @return the value of t_goods.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.unit
     *
     * @param unit the value for t_goods.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.producted_date
     *
     * @return the value of t_goods.producted_date
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getProductedDate() {
        return productedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.producted_date
     *
     * @param productedDate the value for t_goods.producted_date
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setProductedDate(Date productedDate) {
        this.productedDate = productedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.indate
     *
     * @return the value of t_goods.indate
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.indate
     *
     * @param indate the value for t_goods.indate
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setIndate(Integer indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.lastCatId
     *
     * @return the value of t_goods.lastCatId
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getLastcatid() {
        return lastcatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.lastCatId
     *
     * @param lastcatid the value for t_goods.lastCatId
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setLastcatid(Integer lastcatid) {
        this.lastcatid = lastcatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.catPath
     *
     * @return the value of t_goods.catPath
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public String getCatpath() {
        return catpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.catPath
     *
     * @param catpath the value for t_goods.catPath
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCatpath(String catpath) {
        this.catpath = catpath == null ? null : catpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.isDel
     *
     * @return the value of t_goods.isDel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.isDel
     *
     * @param isdel the value for t_goods.isDel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_time
     *
     * @return the value of t_goods.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_time
     *
     * @param createTime the value for t_goods.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}