package com.meetingm.mini.pro.entity;

import java.util.Date;

public class GoodsSell {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.goodsid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.sellsuser
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer sellsuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.sellstime
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date sellstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.sellNumber
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer sellnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_sell.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.id
     *
     * @return the value of t_goods_sell.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.id
     *
     * @param id the value for t_goods_sell.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.goodsid
     *
     * @return the value of t_goods_sell.goodsid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.goodsid
     *
     * @param goodsid the value for t_goods_sell.goodsid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.sellsuser
     *
     * @return the value of t_goods_sell.sellsuser
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getSellsuser() {
        return sellsuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.sellsuser
     *
     * @param sellsuser the value for t_goods_sell.sellsuser
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setSellsuser(Integer sellsuser) {
        this.sellsuser = sellsuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.sellstime
     *
     * @return the value of t_goods_sell.sellstime
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getSellstime() {
        return sellstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.sellstime
     *
     * @param sellstime the value for t_goods_sell.sellstime
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setSellstime(Date sellstime) {
        this.sellstime = sellstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.sellNumber
     *
     * @return the value of t_goods_sell.sellNumber
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getSellnumber() {
        return sellnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.sellNumber
     *
     * @param sellnumber the value for t_goods_sell.sellNumber
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setSellnumber(Integer sellnumber) {
        this.sellnumber = sellnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.unit
     *
     * @return the value of t_goods_sell.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.unit
     *
     * @param unit the value for t_goods_sell.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_sell.create_time
     *
     * @return the value of t_goods_sell.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_sell.create_time
     *
     * @param createTime the value for t_goods_sell.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}