package com.meetingm.mini.pro.entity;

import java.util.Date;

public class GoodsBorrow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.goodsid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.borrowuser
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer borrowuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.direetor
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer direetor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.borrowtime
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date borrowtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.plan_repay_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date planRepayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.borrowNumber
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer borrownumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.statas
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer statas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_borrow.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.id
     *
     * @return the value of t_goods_borrow.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.id
     *
     * @param id the value for t_goods_borrow.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.goodsid
     *
     * @return the value of t_goods_borrow.goodsid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.goodsid
     *
     * @param goodsid the value for t_goods_borrow.goodsid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.borrowuser
     *
     * @return the value of t_goods_borrow.borrowuser
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getBorrowuser() {
        return borrowuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.borrowuser
     *
     * @param borrowuser the value for t_goods_borrow.borrowuser
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setBorrowuser(Integer borrowuser) {
        this.borrowuser = borrowuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.direetor
     *
     * @return the value of t_goods_borrow.direetor
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getDireetor() {
        return direetor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.direetor
     *
     * @param direetor the value for t_goods_borrow.direetor
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setDireetor(Integer direetor) {
        this.direetor = direetor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.borrowtime
     *
     * @return the value of t_goods_borrow.borrowtime
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getBorrowtime() {
        return borrowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.borrowtime
     *
     * @param borrowtime the value for t_goods_borrow.borrowtime
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setBorrowtime(Date borrowtime) {
        this.borrowtime = borrowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.plan_repay_time
     *
     * @return the value of t_goods_borrow.plan_repay_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getPlanRepayTime() {
        return planRepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.plan_repay_time
     *
     * @param planRepayTime the value for t_goods_borrow.plan_repay_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setPlanRepayTime(Date planRepayTime) {
        this.planRepayTime = planRepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.borrowNumber
     *
     * @return the value of t_goods_borrow.borrowNumber
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getBorrownumber() {
        return borrownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.borrowNumber
     *
     * @param borrownumber the value for t_goods_borrow.borrowNumber
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setBorrownumber(Integer borrownumber) {
        this.borrownumber = borrownumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.unit
     *
     * @return the value of t_goods_borrow.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.unit
     *
     * @param unit the value for t_goods_borrow.unit
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.statas
     *
     * @return the value of t_goods_borrow.statas
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getStatas() {
        return statas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.statas
     *
     * @param statas the value for t_goods_borrow.statas
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setStatas(Integer statas) {
        this.statas = statas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_borrow.create_time
     *
     * @return the value of t_goods_borrow.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_borrow.create_time
     *
     * @param createTime the value for t_goods_borrow.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}