package com.meetingm.mini.pro.entity;

import java.util.Date;

public class GoodsRepaty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_repaty.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_repaty.borrowid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer borrowid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_repaty.repay_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer repayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_repaty.quantity
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private String quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_repaty.status
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_repaty.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_repaty.id
     *
     * @return the value of t_goods_repaty.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_repaty.id
     *
     * @param id the value for t_goods_repaty.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_repaty.borrowid
     *
     * @return the value of t_goods_repaty.borrowid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getBorrowid() {
        return borrowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_repaty.borrowid
     *
     * @param borrowid the value for t_goods_repaty.borrowid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setBorrowid(Integer borrowid) {
        this.borrowid = borrowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_repaty.repay_time
     *
     * @return the value of t_goods_repaty.repay_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getRepayTime() {
        return repayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_repaty.repay_time
     *
     * @param repayTime the value for t_goods_repaty.repay_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setRepayTime(Integer repayTime) {
        this.repayTime = repayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_repaty.quantity
     *
     * @return the value of t_goods_repaty.quantity
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_repaty.quantity
     *
     * @param quantity the value for t_goods_repaty.quantity
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity == null ? null : quantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_repaty.status
     *
     * @return the value of t_goods_repaty.status
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_repaty.status
     *
     * @param status the value for t_goods_repaty.status
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_repaty.create_time
     *
     * @return the value of t_goods_repaty.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_repaty.create_time
     *
     * @param createTime the value for t_goods_repaty.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}