package com.meetingm.mini.pro.entity;

import java.util.Date;

public class SysroleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysrole_user.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysrole_user.userid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysrole_user.roleid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysrole_user.isdel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysrole_user.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysrole_user.id
     *
     * @return the value of t_sysrole_user.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysrole_user.id
     *
     * @param id the value for t_sysrole_user.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysrole_user.userid
     *
     * @return the value of t_sysrole_user.userid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysrole_user.userid
     *
     * @param userid the value for t_sysrole_user.userid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysrole_user.roleid
     *
     * @return the value of t_sysrole_user.roleid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysrole_user.roleid
     *
     * @param roleid the value for t_sysrole_user.roleid
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysrole_user.isdel
     *
     * @return the value of t_sysrole_user.isdel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysrole_user.isdel
     *
     * @param isdel the value for t_sysrole_user.isdel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysrole_user.create_time
     *
     * @return the value of t_sysrole_user.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysrole_user.create_time
     *
     * @param createTime the value for t_sysrole_user.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}