package com.meetingm.mini.pro.entity;

import java.util.Date;
/**
 * 
 * <pre>
 * 
 * </pre>
 * 
 * @author guojz jiazhen.guo@meicloud.com
 * @version 1.00.00
 * 
 *          <pre>
 * 修改记录
 *    修改后版本:     修改人：guojiazhen   修改日期:2018年5月23日     修改内容:
 * </pre>
 */
public class Sysuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.id
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.name
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.sex
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.age
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.mobile
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.phone
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.idcard
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.address
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.isDel
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private Integer isdel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysuser.create_time
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.id
	 * @return  the value of t_sysuser.id
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.id
	 * @param id  the value for t_sysuser.id
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.name
	 * @return  the value of t_sysuser.name
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.name
	 * @param name  the value for t_sysuser.name
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.sex
	 * @return  the value of t_sysuser.sex
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.sex
	 * @param sex  the value for t_sysuser.sex
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.age
	 * @return  the value of t_sysuser.age
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.age
	 * @param age  the value for t_sysuser.age
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.mobile
	 * @return  the value of t_sysuser.mobile
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.mobile
	 * @param mobile  the value for t_sysuser.mobile
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.phone
	 * @return  the value of t_sysuser.phone
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.phone
	 * @param phone  the value for t_sysuser.phone
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.idcard
	 * @return  the value of t_sysuser.idcard
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.idcard
	 * @param idcard  the value for t_sysuser.idcard
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard == null ? null : idcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.address
	 * @return  the value of t_sysuser.address
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.address
	 * @param address  the value for t_sysuser.address
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.isDel
	 * @return  the value of t_sysuser.isDel
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public Integer getIsdel() {
		return isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.isDel
	 * @param isdel  the value for t_sysuser.isDel
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysuser.create_time
	 * @return  the value of t_sysuser.create_time
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysuser.create_time
	 * @param createTime  the value for t_sysuser.create_time
	 * @mbg.generated  Wed May 23 14:48:38 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
