package com.meetingm.mini.pro.entity;

import java.util.Date;

public class UserBinding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_binding.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_binding.wx_id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer wxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_binding.user_id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_binding.isdel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Integer isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_binding.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_binding.id
     *
     * @return the value of t_user_binding.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_binding.id
     *
     * @param id the value for t_user_binding.id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_binding.wx_id
     *
     * @return the value of t_user_binding.wx_id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_binding.wx_id
     *
     * @param wxId the value for t_user_binding.wx_id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setWxId(Integer wxId) {
        this.wxId = wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_binding.user_id
     *
     * @return the value of t_user_binding.user_id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_binding.user_id
     *
     * @param userId the value for t_user_binding.user_id
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_binding.isdel
     *
     * @return the value of t_user_binding.isdel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_binding.isdel
     *
     * @param isdel the value for t_user_binding.isdel
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_binding.create_time
     *
     * @return the value of t_user_binding.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_binding.create_time
     *
     * @param createTime the value for t_user_binding.create_time
     *
     * @mbg.generated Wed May 23 14:48:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}